### ISSUE TITLE
Make Travis tests run on OS X too

### ISSUE THREAD

**Issue by Valloric** [Valloric/ycmd#191]
Travis supports running on OS X now too. [More details](http://docs.travis-ci.com/user/multi-os/).

In theory, this is as simple as adding the following to our `.travis.yml`:

```
os:
  - linux
  - osx
```

In practice, it's much more complicated than that because our `install` section in `.travis.yml` assumes Linux. So we'll probably have to break out the install code into a shell script which looks at the new `TRAVIS_OS_NAME` env var and then does custom OS stuff.

**Comment by puremourning** [comment]
FWIW (and in case it helps) i have to hack the build flags to get the tests to run on my mac.

e.g. https://github.com/puremourning/ycmd-1/commit/f27857e8945a78b2b3d7a2c82d952173f2558965

Even with that there are some failures in the `GetType` tests because the stl implementation differs to gnu. I know I wrote those tests, so happy to change them if (an indeed when) there are failures when running on os x

**Comment by puremourning** [comment]
perhaps we should also migrate to the new container-based architecture too: [more details](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)

**Comment by micbou** [comment]
I tried but we are stuck with a too old version of mono for the C# completer. We need to wait Travis whitelisting a APT source with recent versions of mono or updating to ubuntu 14.04.

**Comment by puremourning** [comment]
has whitelisting been requested?

i just had a crack at enabling OS X build and it automatically moved to container architecture. I've forced it back, but it doesn't look like it is building on OS X.

**Comment by micbou** [comment]
This [package repository](https://github.com/travis-ci/apt-source-whitelist/pull/94) has been requested and it should be enough for us.

**Comment by micbou** [comment]
From this [page](http://docs.travis-ci.com/user/multi-os/):
> This feature needs to be enabled manually. If you wish to take advantage of this feature, please send email to support@travis-ci.com, indicating which repository you would like to have it enabled.

Seems that we need to contact Travis support.

**Comment by puremourning** [comment]
Also, python projects don't work on OS X:

from running the yaml through http://lint.travis-ci.org

> in os section: dropping osx, does not support python
> your repository must be feature flagged for the os setting to be used
> specified compiler, but setting is not relevant for python

**Comment by puremourning** [comment]
FWIW here is the issue tracking OS X python support.  https://github.com/travis-ci/travis-ci/issues/2312

There are workarounds, but it means we would lose the python build version matrix. We'd probably skip to using env var matrices and manually configure virtualenvs on the slaves

e.g.

```yaml
language: c++
os:
  - linux
  - osx
osx_image: xcode6.4
sudo: required
before_install:
  - git submodule update --init --recursive
install:
  # source because it sets up env vars on some platforms
  - source ./travis_install.sh
compiler:
  - gcc
script: ./run_tests.sh
env:
  - USE_CLANG_COMPLETER="true" PYTHON_VERSION="2.6"
  - USE_CLANG_COMPLETER="false" PYTHON_VERSION="2.7"
  - USE_CLANG_COMPLETER="true" PYTHON_VERSION="2.6"
  - USE_CLANG_COMPLETER="false" PYTHON_VERSION="2.7"
```

Though we then have to implement the multiple python version stuff ourselves, which is a pain.
